### ISSUE TITLE
System Requirements 

### ISSUE THREAD

**Issue by Vulcan-07** [deKibi/blum-game-ai-clicker#4]
If i have 6 cores and base speed of 2.10 GHz will this script work ?
![1723708550462525399527916122918](https://github.com/user-attachments/assets/71624ffb-346d-4262-9dc7-68569bda595d)
![17237085956934147769592802699111](https://github.com/user-attachments/assets/84c7804b-a887-4fe3-8e87-704baeba313e)

**Comment by deKibi** [comment]
The script was tested on 6 cores, 12 threads with a base frequency of 3 GHz and worked very poorly.

I plan to do some optimization, approximately from next week, I will try to make it possible to run on devices with 6 cores.

You can try for now, but most likely there will be a small farm and crashes.
