### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by deKibi** [deKibi/blum-game-ai-clicker#5]
## Caused by
- https://github.com/deKibi/blum-game-ai-clicker/issues/4

## AC
Now the script works poorly even on average systems. The code has constant checks that are not needed in certain moments.

It is also possible to introduce a "light mode" with less stars farm and delays, but for weak and average devices.

## Definition of done
The script runs on a device with 6 cores, 3 GHz. The average farm from 10 games is not less than 100 points

**Comment by Vulcan-07** [comment]
Ya like randomly select limited stars not all available on screen, with some random time delay in interval (0.02,0.1)sec

It will make the Humanize script 

I have also trained Yolov8 Model and i have it's dataset and i have also a python script for it but facing some minor issues by any guess it helps you.
Share your mail so i can send you the model files , script and dataset..

**Comment by deKibi** [comment]
killed issue
